### PR TITLE
Update install-db.sh script

### PR DESCRIPTION
**Pull request by JoseGoncalves**
Hi @miken32.
Thanks for keeping A2Billing alive!
While trying to install it on a Debian 12 machine I've found that the changes on this PR are needed to successfully create the database.

### CODE REVIEW

**Comment by miken32** [comment]
Hi José, `ALTER IGNORE TABLE` was an ancient, non-standard syntax extension. It was deprecated in MySQL 5.6, removed in 5.7.4, and would cause errors in modern versions. I will update that install script though. 

That said, I am getting pretty frustrated with the state of this code. Every update uncovers another piece of fragile ugly code. We do use this project in production, but we are only using about 10% of the functionality included (really just creating accounts, doing LCR, and adding billing CDRs) and I'm likely going to just give up and move us to something I write from the ground up.

**Comment by JoseGoncalves** [comment]
Hi Michael. I've updated the PR to perform the data truncation in a way that is compatible with recent MySQL versions.

Not very good news to know that you are wondering in giving up of this code. From what you have reported that is currently operational, it seems that it will also suit my needs. I'll try to fix some issues that I'm encountering in the web interface to see if I can make it minimal operational for my use case.

**Review by miken32 — APPROVED** [review]
Please remove the changes to the SQL files and I'll push the change to the install script.

**Comment by miken32** [comment]
I've enabled issues on this fork if you want to report any big issues with the code as far as the admin interface and managing settings, customers, rates, plans, etc. But as I said I'm not interested in fixing things like the agent/customer interface, payments, calling cards, etc.

**Comment by JoseGoncalves** [comment]
Same interests in this side... meanwhile I've found and corrected some minor initialization issues that prevented the web UI to properly work with an "empty" DB. I can issue a PR for these, in case you are interested.

Still with an "empty" DB, the only thing that is missing for me is the `Admins` interface, that does not give me any PHP error but renders a completely blank screen (the header and sidebar disapears). I'm going to dig a bit deeper, but if I not find the cause (I'm a PHP noob) I'll probably create an Issue.

**Comment by miken32** [comment]
Ah that would explain it; it's probably been 15 years since I did an install with an empty database. Pre-populating the DB with our admins and rates is done as part of our PBX deployment script. The problem is how do you log in to the UI without any admins? I think looking at the PHP error log would give a pretty clear indication where the problem is. Feel free to open an issue if needed though.

**Comment by JoseGoncalves** [comment]
> it's probably been 15 years since I did an install with an empty database.

That explains why you did not encounter the issues that I had.

> The problem is how do you log in to the UI without any admins?

Using the default admin setup by the `install-db.sh` script; user: root, password: changepassword.
That is even documented in [INSTALL.rst](https://github.com/radiusone/a2billing/blob/develop/INSTALL.rst#12-default-passwords-and-access-info)

> I think looking at the PHP error log would give a pretty clear indication where the problem is

For the `Admins` section (with an empty DB) no error (or warning) apears on the log.

**Comment by JoseGoncalves** [comment]
> For the Admins section (with an empty DB) no error (or warning) apears on the log.

Found the issue... the default Admin user (root) is created without `Admin::ACX_MODIFY_ADMINS` permission, what causes that blank page. I think that the root user should be created with all permissions set, in order someone that starts with an empty DB can have access to everything in the UI. That default Admin is created in [a2billing-schema-v1.4.0.sql](https://github.com/radiusone/a2billing/blob/develop/DataBase/mysql-5.x/a2billing-schema-v1.4.0.sql#L8311).

**Pull request merged**
